/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author orgfe
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    double valor1, valor2;
    String sinal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_sete = new javax.swing.JButton();
        bt_oito = new javax.swing.JButton();
        bt_nove = new javax.swing.JButton();
        bt_CE = new javax.swing.JButton();
        bt_adicao = new javax.swing.JButton();
        bt_cinco = new javax.swing.JButton();
        bt_seis = new javax.swing.JButton();
        bt_C = new javax.swing.JButton();
        bt_subtracao = new javax.swing.JButton();
        bt_quatro = new javax.swing.JButton();
        bt_tres = new javax.swing.JButton();
        bt_igual = new javax.swing.JButton();
        bt_multiplicacao = new javax.swing.JButton();
        bt_um = new javax.swing.JButton();
        bt_dois = new javax.swing.JButton();
        bt_ponto = new javax.swing.JButton();
        bt_divsao = new javax.swing.JButton();
        bt_zero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        bt_sete.setText("7");
        bt_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seteActionPerformed(evt);
            }
        });

        bt_oito.setText("8");
        bt_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_oitoActionPerformed(evt);
            }
        });

        bt_nove.setText("9");
        bt_nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_noveActionPerformed(evt);
            }
        });

        bt_CE.setText("CE");
        bt_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CEActionPerformed(evt);
            }
        });

        bt_adicao.setText("+");
        bt_adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicaoActionPerformed(evt);
            }
        });

        bt_cinco.setText("5");
        bt_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cincoActionPerformed(evt);
            }
        });

        bt_seis.setText("6");
        bt_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seisActionPerformed(evt);
            }
        });

        bt_C.setText("C");
        bt_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CActionPerformed(evt);
            }
        });

        bt_subtracao.setText("-");
        bt_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_subtracaoActionPerformed(evt);
            }
        });

        bt_quatro.setText("4");
        bt_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quatroActionPerformed(evt);
            }
        });

        bt_tres.setText("3");
        bt_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tresActionPerformed(evt);
            }
        });

        bt_igual.setText("=");
        bt_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_igualActionPerformed(evt);
            }
        });

        bt_multiplicacao.setText("*");
        bt_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multiplicacaoActionPerformed(evt);
            }
        });

        bt_um.setText("1");
        bt_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_umActionPerformed(evt);
            }
        });

        bt_dois.setText("2");
        bt_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_doisActionPerformed(evt);
            }
        });

        bt_ponto.setText(".");
        bt_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pontoActionPerformed(evt);
            }
        });

        bt_divsao.setText("/");
        bt_divsao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divsaoActionPerformed(evt);
            }
        });

        bt_zero.setText("0");
        bt_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_zeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_um, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_quatro, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(bt_sete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_cinco, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(bt_oito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_nove, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(bt_seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_CE, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_divsao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_subtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_adicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_C, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_divsao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_zeroActionPerformed
        txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_bt_zeroActionPerformed

    private void bt_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seteActionPerformed
        txtResultado.setText(txtResultado.getText()+"7");
    }//GEN-LAST:event_bt_seteActionPerformed

    private void bt_adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicaoActionPerformed
        valor1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        sinal = "soma";
    }//GEN-LAST:event_bt_adicaoActionPerformed

    private void bt_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_umActionPerformed
        txtResultado.setText(txtResultado.getText()+"1");
    }//GEN-LAST:event_bt_umActionPerformed

    private void bt_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_doisActionPerformed
         txtResultado.setText(txtResultado.getText()+"2");
    }//GEN-LAST:event_bt_doisActionPerformed

    private void bt_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tresActionPerformed
         txtResultado.setText(txtResultado.getText()+"3");
    }//GEN-LAST:event_bt_tresActionPerformed

    private void bt_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quatroActionPerformed
         txtResultado.setText(txtResultado.getText()+"4");
    }//GEN-LAST:event_bt_quatroActionPerformed

    private void bt_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cincoActionPerformed
         txtResultado.setText(txtResultado.getText()+"5");
    }//GEN-LAST:event_bt_cincoActionPerformed

    private void bt_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seisActionPerformed
         txtResultado.setText(txtResultado.getText()+"6");
    }//GEN-LAST:event_bt_seisActionPerformed

    private void bt_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_oitoActionPerformed
         txtResultado.setText(txtResultado.getText()+"8");
    }//GEN-LAST:event_bt_oitoActionPerformed

    private void bt_noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_noveActionPerformed
         txtResultado.setText(txtResultado.getText()+"9");
    }//GEN-LAST:event_bt_noveActionPerformed

    private void bt_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pontoActionPerformed
        txtResultado.setText(txtResultado.getText()+".");
    }//GEN-LAST:event_bt_pontoActionPerformed

    private void bt_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CEActionPerformed
        txtResultado.setText(""); 
    }//GEN-LAST:event_bt_CEActionPerformed

    private void bt_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_igualActionPerformed
        valor2 = Double.parseDouble(txtResultado.getText());
        if(sinal == "soma"){
            txtResultado.setText(String.valueOf(valor1 + valor2));
        }
        
        if(sinal == "menos"){
            txtResultado.setText(String.valueOf(valor1 - valor2));
        }
        
        if(sinal == "vezes"){
            txtResultado.setText(String.valueOf(valor1 * valor2));
        }
        
        if(sinal == "dividir"){
            txtResultado.setText(String.valueOf(valor1 / valor2));
        }
    }//GEN-LAST:event_bt_igualActionPerformed

    private void bt_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_subtracaoActionPerformed
        valor1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        sinal = "menos";
    }//GEN-LAST:event_bt_subtracaoActionPerformed

    private void bt_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multiplicacaoActionPerformed
        valor1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        sinal = "vezes";
    }//GEN-LAST:event_bt_multiplicacaoActionPerformed

    private void bt_divsaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divsaoActionPerformed
        valor1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        sinal = "dividir";
    }//GEN-LAST:event_bt_divsaoActionPerformed

    private void bt_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CActionPerformed
        valor1 = 0;
        valor2 = 0;
        txtResultado.setText("");
    }//GEN-LAST:event_bt_CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_C;
    private javax.swing.JButton bt_CE;
    private javax.swing.JButton bt_adicao;
    private javax.swing.JButton bt_cinco;
    private javax.swing.JButton bt_divsao;
    private javax.swing.JButton bt_dois;
    private javax.swing.JButton bt_igual;
    private javax.swing.JButton bt_multiplicacao;
    private javax.swing.JButton bt_nove;
    private javax.swing.JButton bt_oito;
    private javax.swing.JButton bt_ponto;
    private javax.swing.JButton bt_quatro;
    private javax.swing.JButton bt_seis;
    private javax.swing.JButton bt_sete;
    private javax.swing.JButton bt_subtracao;
    private javax.swing.JButton bt_tres;
    private javax.swing.JButton bt_um;
    private javax.swing.JButton bt_zero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
